---
# tasks file for apache


- name: Install epel
  yum:
    name: epel-release
    
- name: Install Mariadb
  yum:
    name: "{{ item }}"
  with_items: "{{ sql_itens }}"
  
- name: Start the Mariadb service
  action: service name=mariadb.service state=started

- name: Create mysql user
  mysql_user:
    name: bob
    password: "12345"
    priv: "*.*:USAGE"
    state: present

# - name: Copy .my.cnf file with root password credentials
#   template: 
#     src: my.cnf
#     dest: '/etc/mysql/my.cnf' 
#     owner: root 
#     mode: 0600    

# -  name: Update mysql root password for all root accounts
#    mariadb_user: 
#      name: root 
#      host: "{{item}}" 
#      password: "{{mysql_root_password}}"
#    with_items:
#     - 127.0.0.1
#     - ::1
#     - localhost