---
# tasks file for apache
- name: Install epel
  yum:
    name: epel-release
    
- name: Install Mysql
  yum:
    name: "{{ item }}"
  with_items: "{{ sql_itens }}"
  
- name: Start the MySQL service
  action: service name=mysql state=started

- name: Create deploy user for mariadb
  mariadb_user: 
    user: "deploy" 
    host: "%" 
    password: "{{mysql_root_password}}" 
    priv: "*.*:ALL,GRANT"

- name: Ensure anonymous users are not in the database
  mariadb_user: 
    user: '' 
    host: $item 
    state: absent
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

# - name: Copy .my.cnf file with root password credentials
#   template: 
#     src: my.cnf
#     dest: '/etc/mysql/my.cnf' 
#     owner: root 
#     mode: 0600    

-  name: Update mysql root password for all root accounts
   mariadb_user: 
     name: root 
     host: "{{item}}" 
     password: "{{mysql_root_password}}"
   with_items:
    - 127.0.0.1
    - ::1
    - localhost